{
	"id": "8e5e6d42-a0fa-11e3-b09a-080027f2d077",
	"advisories": [
		{
			"content": {
				"id": "8e5e6d42-a0fa-11e3-b09a-080027f2d077",
				"title": "Python -- buffer overflow in socket.recvfrom_into()",
				"description": "\n\t<p>Vincent Danen via Red Hat Issue Tracker reports:</p>\n\t<blockquote cite=\"https://bugzilla.redhat.com/show_bug.cgi?id=1062370\">\n\t  <p>A vulnerability was reported in Python's socket module, due to a\n\t   boundary error within the sock_recvfrom_into() function, which could be\n\t   exploited to cause a buffer overflow.  This could be used to crash a\n\t   Python application that uses the socket.recvfrom_info() function or,\n\t   possibly, execute arbitrary code with the permissions of the user\n\t   running vulnerable Python code.</p>\n\n\t  <p>This vulnerable function, socket.recvfrom_into(), was introduced in\n\t   Python 2.5.  Earlier versions are not affected by this flaw.</p>\n\t</blockquote>\n      ",
				"references": [
					{
						"source": "vuxml.freebsd.org",
						"url": "http://bugs.python.org/issue20246"
					},
					{
						"source": "vuxml.freebsd.org",
						"url": "http://www.securityfocus.com/bid/65379"
					},
					{
						"source": "vuxml.freebsd.org",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062370"
					},
					{
						"source": "vuxml.freebsd.org",
						"url": "https://mail.python.org/pipermail/python-dev/2014-February/132758.html"
					},
					{
						"source": "vuxml.freebsd.org",
						"url": "https://www.vuxml.org/freebsd/8e5e6d42-a0fa-11e3-b09a-080027f2d077.html"
					}
				],
				"published": "2014-03-01T00:00:00Z"
			},
			"ecosystems": [
				"freebsd"
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2014-1912",
				"references": [
					{
						"source": "vuxml.freebsd.org",
						"url": "https://www.cve.org/CVERecord?id=CVE-2014-1912"
					}
				]
			},
			"ecosystems": [
				"freebsd"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "freebsd",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python27"
						},
						"affected": {
							"type": "freebsd-pkg",
							"range": [
								{
									"le": "2.7.6_3"
								}
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python31"
						},
						"affected": {
							"type": "freebsd-pkg",
							"range": [
								{
									"le": "3.1.5_10"
								}
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python32"
						},
						"affected": {
							"type": "freebsd-pkg",
							"range": [
								{
									"le": "3.2.5_7"
								}
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python33"
						},
						"affected": {
							"type": "freebsd-pkg",
							"range": [
								{
									"le": "3.3.3_2"
								}
							]
						}
					}
				]
			}
		}
	],
	"data_source": "freebsd"
}
